### ISSUE TITLE
M-x font-lock-studio fails with customized display-buffer-alist

### ISSUE THREAD

**Issue by wasamasa** [Lindydancer/font-lock-studio#1]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  font-lock-studio-show-source()
  font-lock-studio-region(1 25772 nil)
  font-lock-studio(nil)
  call-interactively(font-lock-studio record nil)
  command-execute(font-lock-studio record)
```

It took me some time to realize that this is because I'm using [shackle](https://github.com/wasamasa/shackle) and have configured it to select windows after displaying them.  With it disabled, the error doesn't occur which suggests that the root cause of this is font-lock-studio relying on the default Emacs behavior.

**Comment by Lindydancer** [comment]
Hi!

I just took a look at it. Yes, you are correct, font-lock studio doesn't
expect display-buffer to change the current buffer. The problem occurs in
the following code `font-lock-studio-show-source' where it first display a
buffer the tries to access buffer local variables of the buffer it was in
before the call.

However, the documentation of `display-buffer' says the following:

```
"Display BUFFER-OR-NAME in some window, without selecting it."
```

In this light, I don't think font-lock-studio has done anything wrong, and
the problem should be fixed on the shackle side.

There are a number of ways you could handle this:
- Set the window you want to be active, but restore current buffer to the
  original buffer. At the end of the display loop, Emacs will select the
  buffer of the selected window, so you will (hopefully) get the effect you
  are after without breaking existing packages.
- Postpone the selection of the window until a suitable redisplay or post
  command hook.

Alternatively, you could add a shackle exclude rule for font-lock studio
buffers.

Sincerely,
    Anders Lindgren

**Comment by wasamasa** [comment]
I am fully aware that I could just add an exception rule that avoids selecting font lock studio buffers.  What I've tried pointing out here is that using `display-buffer` and assuming that anything more than the buffer being displayed is not something to be taken for granted as customizing `display-buffer-alist` can violate this assumption.  As I wasn't sure whether this is an inherent limitation of the package or something that could be fixed easily to make it more robust, I've opened this issue.  All I'm asking for here is a confirmation whether this mode of operation is intentional and good enough to stay as is.

**Comment by Lindydancer** [comment]
Hi!

In Emacs, there are tons of configuration variables that can be bound to
function that can perform any action -- it doesn't mean it's a good idea...
(Imagine what you could do in a post-command hook...)

I would say making display-buffer change current buffer is a really bad
idea. I just tried to modify shackle so that it doesn't do this (while
still selecting a suitable window) -- it seems to be working as intended
(see attached patch).

On the good side, the error in font-lock-studio is gone. The downside is
that it doesn't work that well in practice, when shackle is active it
selects the window of the source buffer, not the window of the control
buffer, probably because I display the control buffer first and the source
buffer afterwards.

```
-- Anders Lindgren
```

On Fri, Jul 8, 2016 at 7:02 PM, Vasilij Schneidermann <
notifications@github.com> wrote:

> I am fully aware that I could just add an exception rule that avoids
> selecting font lock studio buffers. What I've tried pointing out here is
> that using display-buffer and assuming that anything more than the buffer
> being displayed is not something to be taken for granted as customizing
> display-buffer-alist can violate this assumption. As I wasn't sure
> whether this is an inherent limitation of the package or something that
> could be fixed easily to make it more robust, I've opened this issue. All
> I'm asking for here is a confirmation whether this mode of operation is
> intentional and good enough to stay as is.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Lindydancer/font-lock-studio/issues/1#issuecomment-231414843,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADBjQCVvEpHIrYz_jf7iJc0DctDIA6ZHks5qToKSgaJpZM4JHb2h
> .

**\* shackle-orig.el Fri Jul  8 20:06:40 2016
--- shackle.el  Fri Jul  8 20:06:54 2016

---

**\* 424,435 ****
  it to do useful things such as selecting the popped up window
  afterwards and/or inhibiting `quit-window' from deleting the
  window."
!   (let ((window (shackle--display-buffer buffer alist plist)))
!     (when (plist-get plist :inhibit-window-quit)
!       (shackle--inhibit-window-quit window))
!     (when (and (plist-get plist :select) (window-live-p window))
!       (select-window window t))
!     window))

  ;;;###autoload
  (define-minor-mode shackle-mode
--- 424,436 ----
  it to do useful things such as selecting the popped up window
  afterwards and/or inhibiting `quit-window' from deleting the
  window."
!   (save-excursion
!     (let ((window (shackle--display-buffer buffer alist plist)))
!       (when (plist-get plist :inhibit-window-quit)
!         (shackle--inhibit-window-quit window))
!       (when (and (plist-get plist :select) (window-live-p window))
!         (select-window window t))
!       window)))

  ;;;###autoload
  (define-minor-mode shackle-mode

**Comment by wasamasa** [comment]
I take that as a yes then.

**Comment by Lindydancer** [comment]
> I take that as a yes then.
> 
> I honestly didn't understand your original question... However, it is
> designed so that it itself selects the control window, and the package
> doesn't work that well if another window is selected, since the user would
> have to select the control window after each command.

I'm open to changing font-lock-studio so that it plays better with packages
like shackle, e.g. by changing the order in which is displays its buffers.

What do you think about my patch to shackle? I makes the package less
intrusive while retaining its functionality. I'm sure it will make it more
compatible with a lot more packages.

```
-- Anders
```

**Comment by wasamasa** [comment]
Displaying buffers in another order could be a solution to this, yes.  I wouldn't know, otherwise I wouldn't have opened this issue and handed in a patch instead.

As for the patch, it irks me for two reasons.  For one, this use of `save-excursion` is inscrutable as it isn't done to undo movement inside the current buffer.  More importantly, it goes against the very design of this package.  The reason one customizes `display-buffer-alist` is to intentionally change how buffers are displayed, be it on a general or more special-cased basis.  If I run into package-specific issues, chances are that either the package is doing weird things that can be corrected or that the customization runs against how the package is operating.  I've opened this issue to figure out which of the two it is and am fairly sure that I'm dealing with the latter.
