### ISSUE TITLE
[feature-request] Support debugging custom `font-lock-fontify-region-function`

### ISSUE THREAD

**Issue by apteryks** [Lindydancer/font-lock-studio#6]
Hi,

This is very cool and already useful, but I've hit case where the code makes heavy use of a custom `font-lock-fontify-region-function` (see: https://github.com/doublep/logview/blob/master/logview.el#L3240), and it seems there's nothing in either Emacs or this library to help me debug it via Edebug.

Consider this as a feature request to also allow stepping user-provided `font-lock-fontify-region-function` code.

Thank you!

**Comment by Lindydancer** [comment]
Hi!

Thanks for providing feedback on the package.

I would say that this lies outside the scope of font-lock-studio, since it
focuses on debugging font-lock keywords.

However, I believe that you could use edebug to debug your code rather
easily. I haven't tried this myself, but I think the following should work:

* Disable font-lock for all logview buffers.
* Evaluate the function for debugging, e.g. using C-u M-C-x.
* Call your function with parameters that correspond to what font-lock
would use, i.e. the start and end of a region. (You could pass in
(point-min) and (point-max) if you would like to apply it to the entire
buffer.) Plus nil or whatever for _loudly.

Now, you should be able to debug your function.

Unfortunately, this doesn't highlight comments and strings. If this is
important, you can call font-lock-fontify-syntactically-region before you
call your function.


Another approach would be to redesign the package to use keyword-based
rules. You can extend the region using a function in
font-lock-extend-region. If some part of the code is too advanced to be
handled by a plain rule, you can always use a "matcher function" to handle
that. Remember that the "face" field in a font-lock keyword can be an
arbitrary expression, so you can do more advanced things with it that just
apply a single face. The advantage of doing this is that you could use
font-lock-studio to debug your rules. Another advantage is that the code
will be simpler, as there is a lot of stuff you don't need to do manually.

Good luck with your package!

/ Anders Lindgren

**Comment by apteryks** [comment]
Hi Anders, 

Thanks a lot for the debugging tips!  I've since deciced to not base my mode on logview because of this problem and others, but if I encounter this situation again I'll refer to your answer to attempt debugging :-).

I'll decidedly stick to font-lock keywords for my own mode, for which font-lock-studio helps a lot! `logview` uses a custom `font-lock-fontify-region-function` for performance reason, its author told me.

Thanks again for your thoughtful reply!
